### ISSUE TITLE
是否需要统计开发者名单

### ISSUE THREAD

**Issue by guocheng1106** [lovedb11/big-dog#4]
统计开发者名单有利于我们分工合作。

**Comment by lovedb11** [comment]
我觉得很有必要

**Comment by guocheng1106** [comment]
> 统计开发者名单有利于我们分工合作。

很好的建议

**Comment by guocheng1106** [comment]
问题在这里，已经讨论了：https://github.com/lovedb11/big-dog/issues/4#issue-435361537
